default: btoa wr-1518b-41pkt wr-64b-595pkt
	gcc -O -o btoa btoa.c
	gcc -O -o wr-64b-595pkt wr-64b-595pkt.c
	gcc -O -o wr-1518b-41pkt wr-1518b-41pkt.c

clean:
	rm -f *.o btoa wr-1518b-41pkt wr-64b-595pkt
